### ISSUE TITLE
Request to Add product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [aliyigitbireroglu/flutter-peek-and-pop#3]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. 

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by aliyigitbireroglu** [comment]
Hello Maheshwari, its very nice to hear from you.

I would be glad to share my packages! In addition to this one, you may also like the [snap](https://github.com/aliyigitbireroglu/flutter-snap) package.

I've added the MIT License to both of them so feel free to share them as you wish!

Cheers.

**Comment by maheshwari-1153** [comment]
Hello,

It's our pleasure. I will let you know once we add the product.

Regards,
Maheshwari

**Comment by maheshwari-1153** [comment]
Hello,

We have added your products Flutter Peek & Pop
<https://startflutter.com/themes/peek-pop/> & Flutter Snap
<https://startflutter.com/themes/snap/> in our Start Flutter website.

Please have a look & share your feedback.

Regards,
Maheshwari

**Comment by aliyigitbireroglu** [comment]
Hi again,

Thank you very much, I appreciate. 

Have a nice day!

**Comment by aliyigitbireroglu** [comment]
@maheshwari-1153 
Hello again,

I have made some drastic and useful updates to both of these packages. I just wanted to notify you about these changes in case you would like to update the pages on startflutter.com:)

I also would like it very much if you can take a look at [image-sequence-animator](https://github.com/aliyigitbireroglu/flutter-image-sequence-animator) and [flick](https://github.com/aliyigitbireroglu/flutter-flick).

**Comment by maheshwari-1153** [comment]
Hello,

Sure , thanks for the update.
I will look through the changes & also thanks for the new product will see
& add it soon.

Regards,
Maheshwari
